export const Simples = [
  {
    nome: "Adaga",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Leve",
    preco: "2",
    dano: "1d4",
    critico: "19",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Essa faca afiada é muito usada por ladrões e assassinos, por ser facilmente escondida. Você recebe um bônus de +4 em testes de Ladinagem para escondê-la. Pode ser arremessada."
  },
  {
    nome: "Arco Curto",
    proficiencia: "Simples",
    tipo: "Ataque a Distância",
    empunhadura: "Duas Mãos",
    preco: "30",
    dano: "1d6",
    critico: "x3",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Este arco bastante comum é próprio para caçadas. Exige as duas mãos e é apropriado para manuseio em florestas e ambientes fechados."
  },
  {
    nome: "Azagala",
    proficiencia: "Simples",
    tipo: "Ataque a Distância",
    empunhadura: "Uma Mão",
    preco: "1",
    dano: "1d6",
    critico: "x2",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Lança curta e delgada usada como arma de arremesso por povos caçadores. Também conhecida como javelin."
  },
  {
    nome: "Bordão",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "-",
    dano: "1d6/1d6",
    critico: "x2",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "2",
    descricao: "Um cajado apreciado por viajantes e camponeses. É uma arma dupla (pode ser usada com Combater com Duas Armas) e uma arma de monge (usável com rajada de golpes)."
  },
  {
    nome: "Clava",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "-",
    dano: "1d6",
    critico: "x2",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Um pedaço de madeira empunhado como arma, geralmente usado por bárbaros. Sendo fácil de conseguir, seu preço é zero."
  },
  {
    nome: "Espada curta",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Leve",
    preco: "10",
    dano: "1d6",
    critico: "19",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "O mais comum tipo de espada, muito usada por milicianos e soldados rasos. Possui entre 40 a 50 cm de comprimento."
  },
  {
    nome: "Folce",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Leve",
    preco: "4",
    dano: "1d6",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Diferente da ferramenta agrícola, uma foice de combate é bem mais forte e balanceada. Capaz de infligir ferimentos precisos e letais."
  },
  {
    nome: "Funda",
    proficiencia: "Simples",
    tipo: "Ataque a Distância",
    empunhadura: "Uma Mão",
    preco: "-",
    dano: "1d4",
    critico: "x2",
    alcance: "Médio",
    tipoDano: "Impacto",
    espacos: "1",
    descricao: "Usada para arremessar balas de metal. Na falta de munição, pode disparar pedras comuns (dano reduzido para 1d3). Você aplica seu modificador de Força a jogadas de dano."
  },
  {
    nome: "Lança",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "2",
    dano: "1d6",
    critico: "x2",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Qualquer arma feita com haste de madeira e ponta afiada. Muito comum entre raças menos civilizadas. Pode ser arremessada."
  },
  {
    nome: "Méça",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "12",
    dano: "1d8",
    critico: "x2",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "1",
    descricao: "Bastão metálico com peso cheio de protuberâncias na extremidade. Muito usada por clérigos que fazem votos de não derramar sangue."
  },
  {
    nome: "Pique",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "2",
    dano: "1d8",
    critico: "x2",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Basicamente uma lança muito longa. Preferida por guardas medrosos que não querem ficar perto de inimigos."
  },
  {
    nome: "Porrete",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Leve",
    preco: "2",
    dano: "1d6",
    critico: "x2",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "1",
    descricao: "Pedaço sólido de madeira coberto por lã. Causa dano não letal."
  },
  {
    nome: "Tacape",
    proficiencia: "Simples",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "-",
    dano: "1d10",
    critico: "x2",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "2",
    descricao: "Versão mais perigosa da clava, maior e/ou com pregos."
  },
  {
    nome: "Zarabatana",
    proficiencia: "Simples",
    tipo: "Ataque a Distância",
    empunhadura: "Uma Mão",
    preco: "5",
    dano: "1d3",
    critico: "x2",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Pequeno tubo oco usado para disparar dardos. Excelente para inocular venenos; a CD para resistir ao veneno aumenta em +2."
  }
];

export const Marcial = [
  {
    nome: "Alabarda",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "10",
    dano: "1d10",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte/Perfuração",
    espacos: "2",
    descricao: "Arma composta por longa haste com peça pontiaguda e lâmina em forma de meia-lua. Considerada a arma de infantaria mais eficaz contra invasores em fortificações."
  },
  {
    nome: "Alfange",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "75",
    dano: "2d8",
    critico: "18",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "2",
    descricao: "Espada de lâmina muito larga e curva, usada por guerreiros do Deserto."
  },
  {
    nome: "Arco Longo",
    proficiencia: "Marcial",
    tipo: "Ataque a Distância",
    empunhadura: "Duas Mãos",
    preco: "100",
    dano: "1d8",
    critico: "x3",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Arco reforçado com altura de uma pessoa. Permite aplicar modificador de Força às rolagens de dano. Exige as duas mãos e não pode ser usado montado."
  },
  {
    nome: "Besta Leve",
    proficiencia: "Marcial",
    tipo: "Ataque a Distância",
    empunhadura: "Uma Mão",
    preco: "35",
    dano: "1d8",
    critico: "19",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Arco montado sobre coronha de madeira com gatilho. Recarregar é uma ação de movimento. Exige as duas mãos para usar."
  },
  {
    nome: "Besta Pesada",
    proficiencia: "Marcial",
    tipo: "Ataque a Distância",
    empunhadura: "Duas Mãos",
    preco: "50",
    dano: "1d12",
    critico: "19",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Versão maior e mais potente da besta leve. Recarregar é uma ação padrão."
  },
  {
    nome: "Cimitarra",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "15",
    dano: "1d6",
    critico: "18",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Espada com lâmina curva, leve e muito afiada. O talento Acuidade com Arma se aplica à cimitarra."
  },
  {
    nome: "Espada Longa",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "15",
    dano: "1d8",
    critico: "19",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Espadas com 85 cm a 1,15 m de comprimento. Diferenciam-se das bastardas pelo tamanho da empunhadura."
  },
  {
    nome: "Florete",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "20",
    dano: "1d6",
    critico: "18",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Espada de lâmina fina e afiada, muito precisa. O talento Acuidade com arma se aplica."
  },
  {
    nome: "Gadanho",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "18",
    dano: "2d4",
    critico: "x4",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "2",
    descricao: "Ferramenta agrícola, versão maior da foice. Foi criada para ceifar cereais, mas também pode ceifar vidas."
  },
  {
    nome: "Glácio",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "12",
    dano: "1d6",
    critico: "19/x3",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Espada de lâmina curta e pesada sem guarda. Arma padrão dos legionários do Império de Tauron."
  },
  {
    nome: "Lança Montada",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "10",
    dano: "1d8",
    critico: "x3",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Se estiver montado, pode ser usada com uma mão. Em investida montada, causa +2d8 pontos de dano (não multiplicado em crítico)."
  },
  {
    nome: "Machado de Batalha",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "10",
    dano: "1d8",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Poderosa arma capaz de causar ferimentos terríveis, diferente de machados comuns para cortar árvores."
  },
  {
    nome: "Machado de Guerra",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "20",
    dano: "1d12",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "2",
    descricao: "Imenso machado com lâmina dupla, uma das armas mais perigosas que existem."
  },
  {
    nome: "Machadinha",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Leve",
    preco: "6",
    dano: "1d6",
    critico: "x3",
    alcance: "Curto",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Ferramenta útil para cortar madeira e inimigos. Pode ser arremessada."
  },
  {
    nome: "Mangual",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "8",
    dano: "1d8",
    critico: "x2",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "1",
    descricao: "Arma composta por haste metálica ligada a corrente e esfera de aço. Fornece +4 em jogadas de ataque para desarmar."
  },
  {
    nome: "Martelo de Guerra",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "12",
    dano: "1d8",
    critico: "x3",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "1",
    descricao: "Muito eficiente contra esqueletos e mortos-vivos. Arma preferida de anões que recusam machados."
  },
  {
    nome: "Moritante",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "50",
    dano: "2d6",
    critico: "19",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "2",
    descricao: "Enorme espada de 1,5m de comprimento, uma arma poderosa."
  },
  {
    nome: "Neko-ite",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Leve",
    preco: "10",
    dano: "1d4",
    critico: "19",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Luva com garras metálicas. Fornece +2 em testes de Atletismo para escalar e conta como mão livre para escalada."
  },
  {
    nome: "Picareta",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "8",
    dano: "1d6",
    critico: "x4",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Ferramenta com cabeça de metal pontiaguda. Usada em minas e escalada no gelo para prover pontos de fixação."
  },
  {
    nome: "Teisubo",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "20",
    dano: "1d10",
    critico: "x2",
    alcance: "-",
    tipoDano: "Impacto",
    espacos: "2",
    descricao: "Versão mais pesada e sofisticada do tacape. Fornece +2 em testes para derrubar ou empurrar."
  },
  {
    nome: "Tridente",
    proficiencia: "Marcial",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "15",
    dano: "1d8",
    critico: "x2",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Lança com três pontas favorita de gladiadores. Fornece +4 em jogadas de ataque para derrubar."
  }
];

export const Exotica = [
  {
    nome: "Açoite Fintroll",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "30",
    dano: "1d8",
    critico: "x2",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Feito de tiras de couro com farpas de aço. Uma criatura que sofra dano sofre –2 em testes de perícia e dano por 1 rodada."
  },
  {
    nome: "Anpão",
    proficiencia: "Exótica",
    tipo: "Ataque a Distância",
    empunhadura: "Uma Mão",
    preco: "30",
    dano: "1d10",
    critico: "x3",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Arpão de pesca convertido em arma. Se causar dano, fica preso no alvo. Enquanto segura a corda, pode impedir movimentos além de 9m."
  },
  {
    nome: "Chicote",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "2",
    dano: "1d3",
    critico: "x2",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Pode atacar inimigos a até 4,5m e enroscar-se em adversários. Fornece +2 em testes para derrubar ou desarmar."
  },
  {
    nome: "Corrente de Espinhos",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "25",
    dano: "2d4/2d4",
    critico: "19",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "2",
    descricao: "Pode atacar inimigos a até 4,5m e enroscar-se em adversários. Arma ágil, dupla e versátil com +2 em testes para derrubar ou desarmar."
  },
  {
    nome: "Espada Bastarda",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "35",
    dano: "1d10/1d12",
    critico: "19",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Maior e mais pesada que a espada longa. Pode ser usada como arma marcial de duas mãos. Tradicional de cavaleiros do Reino da Ordem da Luz."
  },
  {
    nome: "Espada Vespa",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "75",
    dano: "2d8",
    critico: "18",
    alcance: "-",
    tipoDano: "Corte ou Perfuração",
    espacos: "1",
    descricao: "Feita com três ferrões de vespas gigantes. Pode unir os ferrões para corte ou separá-los para perfuração."
  },
  {
    nome: "Katana",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "100",
    dano: "1d10",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Espada tradicional samurai com lâmina levemente curva. Pode ser usada como arma marcial de duas mãos. Arma ágil."
  },
  {
    nome: "Lança de Fogo",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "1000",
    dano: "Especial",
    critico: "Especial",
    alcance: "Especial",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Arma híbrida: modo corpo-a-corpo (1d10, x3) ou arma de fogo (2d8, 19/x3, médio). Ao acertar ataque corpo-a-corpo, pode disparar bala (+2d8). Exige proficiência em armas de fogo para modo de disparo."
  },
  {
    nome: "Machado Anão",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "30",
    dano: "1d10",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Preferida por guerreiros anões. Pode ser usada como arma marcial de duas mãos."
  },
  {
    nome: "Machado Táurico",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Duas Mãos",
    preco: "50",
    dano: "2d8",
    critico: "x3",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "2",
    descricao: "Arma ancestral dos minotauros. Por ser pesada e desbalanceada, impõe –2 em testes de ataque."
  },
  {
    nome: "Mordida do Diabo",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "30",
    dano: "1d4",
    critico: "x2",
    alcance: "-",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Aparato em forma de mandíbula que pode se destacar e alcançar alvos a 3m. Fornece +2 em testes para agarrar e desarmar."
  },
  {
    nome: "Pistola Punhal",
    proficiencia: "Exótica",
    tipo: "Especial",
    empunhadura: "Uma Mão",
    preco: "300",
    dano: "Especial",
    critico: "Especial",
    alcance: "Especial",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Arma híbrida: modo corpo-a-corpo ágil (1d6, 18) ou arma de fogo (2d6, 19/x3, curto). Ao acertar ataque corpo-a-corpo, pode disparar bala (+2d6). Exige proficiência em armas de fogo."
  },
  {
    nome: "Presa de Serpente",
    proficiencia: "Exótica",
    tipo: "Corpo-a-corpo",
    empunhadura: "Uma Mão",
    preco: "1000",
    dano: "1d8",
    critico: "17",
    alcance: "-",
    tipoDano: "Corte",
    espacos: "1",
    descricao: "Espada de obsidiana. Em crítico, dano aumenta em um passo (antes da multiplicação). Não pode receber melhorias materiais. Arma ágil."
  },
  {
    nome: "Rede",
    proficiencia: "Exótica",
    tipo: "Ataque à Distância",
    empunhadura: "Uma Mão",
    preco: "20",
    dano: "-",
    critico: "-",
    alcance: "Curto",
    tipoDano: "-",
    espacos: "1",
    descricao: "Se acertar, vítima fica enredada (deslocamento reduzido à metade, não pode correr/investir, -2 em Defesa e ataques)."
  },
  {
    nome: "Shuriken",
    proficiencia: "Exótica",
    tipo: "Ataque à Distância",
    empunhadura: "Leve",
    preco: "1",
    dano: "1d4",
    critico: "x2",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "0.5",
    descricao: "Pequenos projéteis em forma de estrelas. Uma vez por rodada, pode gastar 1 PM para ataque adicional contra mesmo alvo."
  }
];

export const Fogo = [
  {
    nome: "Arcabuz",
    proficiencia: "Fogo",
    tipo: "Ataque a Distância",
    empunhadura: "Duas Mãos",
    preco: "800",
    dano: "2d10",
    critico: "19/x3",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Versão mais pesada e potente do mosquete. Recarregar é uma ação padrão. Arma desbalanceada."
  },
  {
    nome: "Bacamarte",
    proficiencia: "Fogo",
    tipo: "Ataque a Distância",
    empunhadura: "Duas Mãos",
    preco: "450",
    dano: "4d6",
    critico: "19/x3",
    alcance: "Especial",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Boca larga espalha munição em cone de 6m. Compare ataque com Defesa de cada criatura na área. Recarregar exige ação completa e 2 balas."
  },
  {
    nome: "Mosquete",
    proficiencia: "Fogo",
    tipo: "Ataque à Distância",
    empunhadura: "Duas Mãos",
    preco: "500",
    dano: "2d8",
    critico: "19/x3",
    alcance: "Médio",
    tipoDano: "Perfuração",
    espacos: "2",
    descricao: "Arma de fogo de uso difícil com poder devastador. Recarregar é ação padrão."
  },
  {
    nome: "Pistola",
    proficiencia: "Fogo",
    tipo: "Ataque à Distância",
    empunhadura: "Leve",
    preco: "250",
    dano: "2d6",
    critico: "19/x3",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Arma de fogo mais comum. Conta como arma leve para Estilo de Duas Armas. Recarregar é ação padrão."
  },
  {
    nome: "Traque",
    proficiencia: "Fogo",
    tipo: "Ataque à Distância",
    empunhadura: "Leve",
    preco: "75",
    dano: "2d6",
    critico: "19/x3",
    alcance: "Curto",
    tipoDano: "Perfuração",
    espacos: "1",
    descricao: "Feita com sucata, falha se errar com resultado ímpar no d20. Recarregar é ação padrão."
  }
];

export const Municao = [
  {
    nome: "Balás de Arma (20)",
    proficiencia: "Fogo",
    tipo: "Ataque a Distância",
    empunhadura: "-",
    preco: "20",
    dano: "-",
    critico: "-",
    alcance: "-",
    tipoDano: "-",
    espacos: "1",
    descricao: "Bolsa com 20 balas (esferas de chumbo) e pólvora para 20 tiros de mosquete/pistola."
  },
  {
    nome: "Balás de Funda (20)",
    proficiencia: "Munição",
    tipo: "-",
    empunhadura: "-",
    preco: "0.5",
    dano: "-",
    critico: "-",
    alcance: "-",
    tipoDano: "-",
    espacos: "1",
    descricao: "Saco com 20 balas esféricas de metal. Recarregar funda é ação de movimento."
  },
  {
    nome: "Dardos (20)",
    proficiencia: "Munição",
    tipo: "-",
    empunhadura: "-",
    preco: "-",
    dano: "-",
    critico: "-",
    alcance: "-",
    tipoDano: "-",
    espacos: "0.5",
    descricao: "Munição para Zarabatana."
  },
  {
    nome: "Flechas (20)",
    proficiencia: "Munição",
    tipo: "-",
    empunhadura: "-",
    preco: "1",
    dano: "-",
    critico: "-",
    alcance: "-",
    tipoDano: "-",
    espacos: "1",
    descricao: "Aljava com 20 flechas (haste de madeira com ponta metálica e penas). Recarregar arco é ação livre."
  },
  {
    nome: "Viroles (20)",
    proficiencia: "Munição",
    tipo: "-",
    empunhadura: "-",
    preco: "2",
    dano: "-",
    critico: "-",
    alcance: "-",
    tipoDano: "-",
    espacos: "1",
    descricao: "Caixa com 10 virotes (setas para besta)."
  }
];

export const Armas = {
  Simples,
  Marcial,
  Exotica,
  Fogo,
  Municao
};