const gerais = {
  name: "Paladino",
  pv: 20,
  addpv: 5,
  pm: 3,
  addpm: 3,
  periciasbasicas: ["LUTA", "VONTADE"],
  obs: "pode começar com dois poderes concedidos inicial",
  periciasrestantes: {
    qtd: 2,
    list: [
      "ADESTRAMENTO",
      "ATLETISMO",
      "CAVALGAR",
      "CURA",
      "DIPLOMACIA",
      "FORTITUDE",
      "GUERRA",
      "INICIATIVA",
      "INTUICAO",
      "NOBREZA",
      "PERCEPCAO",
      "RELIGIAO",
    ],
  },
  proficiencias: ["LEVES", "MARCIAIS", "PESADAS", "ESCUDOS", "SIMPLES"],
  qtdPoderesConcedidos: "all",
  faith: [
    "AZGHER",
    "KHALMYR",
    "LENA",
    "LINWU",
    "MARAH",
    "TANNATOH",
    "THYATIS",
    "VALKARIA",
  ],
  abilities: [
    {
      name: "Abençoado",
      text: "Você soma seu bônus de Carisma no seu total de pontos de mana no 1º nível. Além disso, torna-se devoto de uma divindade disponível para paladinos (Azgher, Khalmyr, Lena, Lin-Wu, Marah, Tanna-Toh, Thyatis, Valkaria). Você deve obedecer às Obrigações & Restrições de seu deus, mas, em troca, ganha os Poderes Concedidos dele. Como alternativa, você pode ser um paladino do bem, lutando em prol da bondade e da justiça como um todo. Não recebe nenhum Poder Concedido, mas não precisa seguir nenhuma Obrigação & Restrição (além do Código do Herói, abaixo).",
      nivel: 1,
    },
    {
      name: "Código de Héroi",
      text: "Você deve sempre manter sua palavra e nunca pode recusar um pedido de ajuda de alguém inocente. Além disso, nunca pode mentir, trapacear ou roubar. Se violar o código, você perde todos os seus PM e só pode recuperá-los a partir do próximo dia.",
      nivel: 1,
    },
    {
      name: "Golpe Divino",
      text: "Quando faz um ataque corpo a corpo, você pode gastar 2 PM para desferir um golpe destruidor. Você soma seu bônus de Carisma no teste de ataque e +1d8 na rolagem de dano. A cada quatro níveis, pode gastar +1 PM para aumentar o dano em +1d8.",
      nivel: 1,
    },
    {
      name: "Cura pelas Mãos",
      text: "partir do 2º nível, você pode gastar uma ação de movimento e 1 PM para curar 1d8+1 pontos de vida de um alvo em alcance corpo a corpo (incluindo você). A cada quatro níveis, você pode gastar +1 PM para aumentar os PV curados em +1d8+1.\nA partir do 6º nível, você pode gastar +1 PM quando usa Cura pelas Mãos para anular uma condição afetando o alvo, entre abalado, apavorado, atordoado, cego, doente, exausto, fatigado ou surdo.\nEsta habilidade também pode causar dano de luz a mortos-vivos, exigindo um ataque desarmado.",
      nivel: 2,
    },
    {
      name: "Aura Sagrada",
      text: "No 3º nível, você pode gastar 1 PM para gerar uma aura com alcance curto a partir de você. A aura emite uma luz dourada e agradável, que ilumina como uma tocha. Além disso, você e os aliados dentro da aura recebem um bônus igual ao seu bônus de Carisma nos testes de resistência. Manter a aura custa 1 PM por turno.",
      nivel: 3,
    },
    {
      name: "Bênção da Justiça",
      text: "No 5º nível, escolha entre égide sagrada e montaria sagrada (Tormenta 20 pág 84). Uma vez feita, esta escolha não pode ser mudada.",
      nivel: 5,
    },
    {
      name: "Vingador Sagrado",
      text: "No 20º nível, você pode gastar uma ação completa e 10 PM para se cobrir de energia divina, assumindo a forma de um vingador sagrado até o fim da cena. Nesta forma, você recebe deslocamento de voo 18m, resistência a dano 20 e soma seu modificador de Carisma em seus testes de ataque e rolagens de dano corpo a corpo.",
      nivel: 20,
    },
  ],
};
