const gerais = {
  name: "Nobre",
  pv: 16,
  addpv: 4,
  pm: 4,
  addpm: 4,
  periciasbasicas: ["DIPLOMACIA OU INTIMIDACAO", "VONTADE"],
  periciasrestantes: {
    qtd: 4,
    list: [
      "ADESTRAMENTO",
      "ATUACAO",
      "CAVALGAR",
      "CONHECIMENTO",
      "DIPLOMACIA",
      "ENGANACAO",
      "FORTITUDE",
      "GUERRA",
      "INICIATIVA",
      "INTIMIDACAO",
      "INTUICAO",
      "INVESTIGACAO",
      "JOGATINA",
      "LUTA",
      "NOBREZA",
      "OFICIO",
      "PERCEPCAO",
      "PONTARIA",
    ],
  },
  proficiencias: ["LEVES", "MARCIAIS", "PESADAS", "ESCUDOS", "SIMPLES"],
  abilities: [
    {
      name: "Autoconfiança",
      text: "Você pode somar seu bônus de Carisma em vez de Destreza na Defesa (mas continua não podendo somar um bônus de atributo na Defesa quando usa armadura pesada).",
      nivel: 1,
    },
    {
      name: "Espólio",
      text: "Você recebe um item a sua escolha com preço de até T$ 2.000.",
      nivel: 1,
    },
    {
      name: "Orgulho",
      text: "Quando faz um teste de perícia, você pode gastar uma quantidade de PM a sua escolha (limitado pelo seu modificador de Carisma). Para cada PM que gastar, recebe +2 no teste.",
      nivel: 1,
    },
    {
      name: "Riqueza",
      text: "No 2º nível, você passa a receber dinheiro de sua família, patrono ou negócios. Uma vez por aventura, você pode fazer um teste de Carisma com um bônus igual ao seu nível de nobre. Você recebe um número de Tibares de ouro igual ao resultado do teste. Por exemplo, um nobre de 5º nível com Carisma 18 (+4) que role um 13 no dado recebe 22 TO. O uso desta habilidade é condicionado a onde e quando você faz o teste, assim como a relação com sua família, patrono ou negócios. Por exemplo, um nobre viajando pelos ermos, isolado da civilização, dificilmente teria como receber dinheiro.",
      nivel: 2,
    },
    {
      name: "Gritar Ordens",
      text: "A partir do 3º nível, você pode gastar uma quantidade de PM a sua escolha (limitado pelo seu bônus de Carisma). Até o início de seu próximo turno, todos os seus aliados em alcance curto recebem um bônus nos testes de perícia igual à quantidade de PM que você gastou.",
      nivel: 3,
    },
    {
      name: "Realeza",
      text: "No 20º nível, sua presença impõe mais do que respeito — impõe veneração. Uma criatura que seja alvo de sua Presença Aristocrática e falhe no teste de Vontade por 10 ou mais se arrepende tanto de ter tentado machucá-lo que passa a lutar ao seu lado (e seguir suas ordens, se puder entendê-lo) pelo resto da cena. Uma criatura que seja reduzida a 0 PV por Palavras Afiadas não sofre este dano; em vez disso, passa a lutar ao seu lado pelo resto da cena.",
      nivel: 20,
    },
  ],
  probDevoto: 0.3,
  faithProbability: [
    "AZGHER",
    "HYNINN",
    "KALLYADRANOCH",
    "KHALMYR",
    "LENA",
    "LINWU",
    "MARAH",
    "SSZZAAS",
    "TANNATOH",
    "VALKARIA",
  ],
};
